from pathlib import Path

def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text(encoding='utf-8')
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{path}: expected exactly one match, found {count}')
    p.write_text(text.replace(old, new), encoding='utf-8')

replace_once('orchestrator/device_auth.py', "        con.execute(\n            '''\n            UPDATE code_devices\n            SET first_seen_at = COALESCE(first_seen_at, activated_at),\n                last_seen_at = COALESCE(last_seen_at, activated_at),\n                active = COALESCE(active, 1)\n            '''\n        )", "        con.execute(\n            '''\n            UPDATE code_devices\n            SET device_name = ?,\n                platform = 'android',\n                app_version = '',\n                first_seen_at = NULL,\n                last_seen_at = NULL,\n                active = COALESCE(active, 1)\n            ''',\n            (DEFAULT_DEVICE_NAME,),\n        )")
replace_once('orchestrator/device_auth.py', '        ORDER BY active DESC, last_seen_at DESC, id ASC', '        ORDER BY active DESC, id ASC')
replace_once('orchestrator/device_auth.py', "            'device_name': _public_device_name(str(row['device_name'] or '')),\n            'platform': 'android',\n            'app_version': '',\n            'first_seen_at': row['first_seen_at'] or '',\n            'last_seen_at': row['last_seen_at'] or '',", "            'device_name': DEFAULT_DEVICE_NAME,\n            'platform': 'android',\n            'app_version': '',\n            'first_seen_at': '',\n            'last_seen_at': '',")
replace_once('orchestrator/device_auth.py', "        'device_name': _public_device_name(str(current['device_name'] or '')),", "        'device_name': DEFAULT_DEVICE_NAME,")
replace_once('orchestrator/device_auth.py', '    safe_device_name = _public_device_name(signed_device_name)', '    safe_device_name = DEFAULT_DEVICE_NAME')
replace_once('orchestrator/device_auth.py', "            con.execute(\n                '''\n                UPDATE code_devices\n                SET device_name = ?,\n                    public_key = ?,\n                    public_key_fingerprint = ?,\n                    platform = ?,\n                    app_version = ?,\n                    first_seen_at = COALESCE(first_seen_at, activated_at, ?),\n                    last_seen_at = ?,\n                    active = 1\n                WHERE id = ?\n                ''',\n                (\n                    safe_device_name,\n                    public_key_base64,\n                    fingerprint,\n                    'android',\n                    app_version.strip()[:32],\n                    current_time,\n                    current_time,\n                    existing['id'],\n                ),\n            )", "            con.execute(\n                '''\n                UPDATE code_devices\n                SET device_name = ?,\n                    public_key = ?,\n                    public_key_fingerprint = ?,\n                    platform = 'android',\n                    app_version = '',\n                    first_seen_at = NULL,\n                    last_seen_at = NULL,\n                    active = 1\n                WHERE id = ?\n                ''',\n                (\n                    DEFAULT_DEVICE_NAME,\n                    public_key_base64,\n                    fingerprint,\n                    existing['id'],\n                ),\n            )")
replace_once('orchestrator/device_auth.py', '                ORDER BY last_seen_at DESC, id ASC', '                ORDER BY id ASC')
replace_once('orchestrator/device_auth.py', "            con.execute(\n                '''\n                INSERT INTO code_devices(\n                    code,\n                    device_id,\n                    activated_at,\n                    device_name,\n                    public_key,\n                    public_key_fingerprint,\n                    platform,\n                    app_version,\n                    first_seen_at,\n                    last_seen_at,\n                    active\n                )\n                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)\n                ''',\n                (\n                    code,\n                    safe_device_id,\n                    current_time,\n                    safe_device_name,\n                    public_key_base64,\n                    fingerprint,\n                    'android',\n                    app_version.strip()[:32],\n                    current_time,\n                    current_time,\n                ),\n            )", "            con.execute(\n                '''\n                INSERT INTO code_devices(\n                    code,\n                    device_id,\n                    activated_at,\n                    device_name,\n                    public_key,\n                    public_key_fingerprint,\n                    platform,\n                    app_version,\n                    first_seen_at,\n                    last_seen_at,\n                    active\n                )\n                VALUES (?, ?, ?, ?, ?, ?, 'android', '', NULL, NULL, 1)\n                ''',\n                (\n                    code,\n                    safe_device_id,\n                    current_time,\n                    DEFAULT_DEVICE_NAME,\n                    public_key_base64,\n                    fingerprint,\n                ),\n            )")
replace_once('orchestrator/device_auth.py', "        current_time = now_iso()\n        con.execute(\n            'UPDATE code_devices SET last_seen_at = ? WHERE id = ?',\n            (current_time, device['id']),\n        )", "        con.execute(\n            'UPDATE code_devices SET last_seen_at = NULL WHERE id = ?',\n            (device['id'],),\n        )")
replace_once('orchestrator/device_auth.py', "        con.execute(\n            'UPDATE code_devices SET last_seen_at = ? WHERE id = ?',\n            (now_iso(), int(row['device_row_id'])),\n        )", "        con.execute(\n            'UPDATE code_devices SET last_seen_at = NULL WHERE id = ?',\n            (int(row['device_row_id']),),\n        )")
replace_once('orchestrator/api.py', 'import concurrent_sessions\nimport sqlite3', 'import concurrent_sessions\nimport hashlib\nimport hmac\nimport sqlite3')
replace_once('orchestrator/api.py', '_attempts: Dict[str, Deque[float]] = defaultdict(deque)', '_attempts: Dict[str, Deque[float]] = defaultdict(deque)\n_RATE_LIMIT_KEY = secrets.token_bytes(32)')
replace_once('orchestrator/api.py', "def client_key(request: Request, payload: ActivationRequest) -> str:\n    forwarded = request.headers.get('x-forwarded-for', '')\n    ip = forwarded.split(',')[0].strip() if forwarded else (request.client.host if request.client else 'unknown')\n    device = payload.deviceId.strip()[:64]\n    return ip + ':' + device", "def client_key(request: Request, payload: ActivationRequest) -> str:\n    forwarded = request.headers.get('x-forwarded-for', '')\n    ip = forwarded.split(',')[0].strip() if forwarded else (request.client.host if request.client else 'unknown')\n    device = payload.deviceId.strip()[:64]\n    material = (ip + '\\0' + device).encode('utf-8')\n    return hmac.new(_RATE_LIMIT_KEY, material, hashlib.sha256).hexdigest()")
replace_once('orchestrator/device_recovery_routes.py', '                con.execute(\n                    "UPDATE code_devices SET last_seen_at = ? WHERE id = ?",\n                    (now_iso(), int(row["id"])),\n                )', '                con.execute(\n                    "UPDATE code_devices SET last_seen_at = NULL WHERE id = ?",\n                    (int(row["id"]),),\n                )')
replace_once('orchestrator/device_recovery_routes.py', '            con.execute(\n                """\n                UPDATE code_devices\n                SET public_key = ?,\n                    public_key_fingerprint = ?,\n                    last_seen_at = ?,\n                    active = 1\n                WHERE id = ?\n                """,\n                (\n                    payload.client_public_key,\n                    new_key_fingerprint,\n                    now_iso(),\n                    int(device["id"]),\n                ),\n            )', '            con.execute(\n                """\n                UPDATE code_devices\n                SET public_key = ?,\n                    public_key_fingerprint = ?,\n                    last_seen_at = NULL,\n                    active = 1\n                WHERE id = ?\n                """,\n                (\n                    payload.client_public_key,\n                    new_key_fingerprint,\n                    int(device["id"]),\n                ),\n            )')
replace_once('emery vpn orchestrator/src/backend/services/xray_credential_service.py', 'config = json.loads(original_text)\noriginal_config = json.loads(original_text)', 'config = json.loads(original_text)\noriginal_config = json.loads(original_text)\nconfig["log"] = {\n    "access": "none",\n    "error": "none",\n    "loglevel": "none",\n    "dnsLog": False,\n}')
replace_once('emery vpn orchestrator/src/backend/services/xray_credential_service.py', '    settings_block["clients"] = [{\n        "id": DATA["client_uuid"],\n        "flow": flow,\n        "email": tag,\n    }]', '    settings_block["clients"] = [{\n        "id": DATA["client_uuid"],\n        "flow": flow,\n    }]')
print('privacy normalization complete')
